### ISSUE TITLE
Update to current cbmc

### ISSUE THREAD

**Issue by rurban** [diffblue/deltacheck#1]
I could find `util/decision_procedure.h` in solvers,
but not `util/i2string.h`, nor `analyses/intervals.h`.

**Comment by peterschrammel** [comment]
This repo is likely compatible with CBMC 5.4 (https://github.com/diffblue/cbmc/releases/tag/cbmc-5.4).
Rebasing this will be a tough job considering that it is more than 15k commits behind.

**Comment by rurban** [comment]
Ok, I'll use that then.
